### ISSUE TITLE
Login input white text in dark mode

### ISSUE THREAD

**Issue by jneurock** [ostera/woolly#1]
The login input text is white in dark mode but the background is also white so it appears to be invisibile.

![image](https://user-images.githubusercontent.com/326789/203280202-94924193-63a7-4a4a-b0e9-46aecb88cd99.png)

![image](https://user-images.githubusercontent.com/326789/203280251-f0f8eddb-b1c9-40d0-b286-53244b9906f5.png)

**Comment by leostera** [comment]
Thanks a million for the issues @jneurock 🤩 Should be fixed now :) let me know if it persists. Closing in the meantime.
